### ISSUE TITLE
👨‍👩‍👧 emoji sequence not display right

### ISSUE THREAD

**Issue by yurenchen000** [susisu/mte-kernel#3]
try on https://susisu.github.io/mte-demo/

/1
paste 👨‍👩‍👧
but shown 👨👩👧

/2
1️⃣ display right, but width seems wrong.

<br>

some emoji sequence:
```
'👨‍👩‍👧'.length -> 8
'👨‍👩‍👧'.split('') -> (8)
 ['\uD83D', '\uDC68', '‍', '\uD83D', '\uDC69', '‍', '\uD83D', '\uDC67']
'👨‍👩‍👧'.match(/\p{Extended_Pictographic}/ug) -> ["👨","👩","👧"]

'1️⃣'.split('') -> (3) ['1', '️', '⃣']
'2️⃣'.split('') -> (3) ['2', '️', '⃣']
```

<br>

ref:
https://stackoverflow.com/a/64007175/4896468
https://unicode.org/Public/emoji/13.0/emoji-sequences.txt

**Comment by yurenchen000** [comment]
https://github.com/mathiasbynens/emoji-regex

foud this pkg good at split emoji chars:

```js
const text = `
\u{231A}: ⌚ default emoji presentation character (Emoji_Presentation)
\u{2194}\u{FE0F}: ↔️ default text presentation character rendered as emoji
\u{1F469}: 👩 emoji modifier base (Emoji_Modifier_Base)
\u{1F469}\u{1F3FF}: 👩🏿 emoji modifier base followed by a modifier
👨‍👩‍👧1️⃣2️⃣
`;

const regex = emojiRegex();
for (const match of text.matchAll(regex)) {
  const emoji = match[0];
  console.log(`Matched sequence ${ emoji } — code points: ${ [...emoji].length }`);
}
```

output as expected:
```
 Matched sequence ⌚ — code points: 1
 Matched sequence ⌚ — code points: 1
 Matched sequence ↔️ — code points: 2
 Matched sequence ↔️ — code points: 2
 Matched sequence 👩 — code points: 1
 Matched sequence 👩 — code points: 1
 Matched sequence 👩🏿 — code points: 2
 Matched sequence 👩🏿 — code points: 2
 Matched sequence 👨‍👩‍👧 — code points: 5
 Matched sequence 1️⃣ — code points: 3
 Matched sequence 2️⃣ — code points: 3
```

**Comment by susisu** [comment]
Hi, @yurenchen000.

I am aware of the issues you reported, but this repository is no longer actively maintained.

Fortunately, there is a project that has been forked from this repository and is being actively maintained:

- https://github.com/tgrosinger/md-advanced-tables

Please give it a try, and consider contributing to it if you are interested :)

**Comment by yurenchen000** [comment]
> @susisu 
> * https://github.com/tgrosinger/md-advanced-tables
> 
> Please give it a try, and consider contributing to it if you are interested :)

Thanks, It works perfect !
